-- Ajustes aplicados logo depois de ModeloLogicoHorizon.sql, sem editar o modelo.
-- A troca de DATETIME por TIMESTAMP é feita antes, em memória, por src/db/esquema_horizon.py,
-- porque o CREATE TABLE original falha no PostgreSQL.

-- 1. Ids gerados pelo banco nas tabelas com chave substituta.
--    unidades_organizacionais, grupos_pesquisa e artigos herdam o id da tabela-mãe e ficam de fora.
ALTER TABLE pessoas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE emails_pessoa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE formacoes_academicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE premios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE idiomas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tipos_formacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE organizacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE vinculos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE papeis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE equipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE membros_equipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE iniciativas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tipos_iniciativa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE participantes_iniciativa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE bolsas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE producoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tipos_producao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE areas_conhecimento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Títulos e nomes sem o limite de 255 caracteres (títulos de projeto e de produção passam disso).
ALTER TABLE pessoas ALTER COLUMN nome TYPE TEXT;
ALTER TABLE perfis_lattes ALTER COLUMN nomes_citacao TYPE TEXT;
ALTER TABLE formacoes_academicas ALTER COLUMN curso TYPE TEXT;
ALTER TABLE formacoes_academicas ALTER COLUMN titulo_tese TYPE TEXT;
ALTER TABLE premios ALTER COLUMN titulo TYPE TEXT;
ALTER TABLE idiomas ALTER COLUMN nome TYPE TEXT;
ALTER TABLE tipos_formacao ALTER COLUMN nome TYPE TEXT;
ALTER TABLE organizacoes ALTER COLUMN nome TYPE TEXT;
ALTER TABLE papeis ALTER COLUMN nome TYPE TEXT;
ALTER TABLE equipes ALTER COLUMN nome TYPE TEXT;
ALTER TABLE iniciativas ALTER COLUMN nome TYPE TEXT;
ALTER TABLE tipos_iniciativa ALTER COLUMN nome TYPE TEXT;
ALTER TABLE bolsas ALTER COLUMN nome TYPE TEXT;
ALTER TABLE producoes ALTER COLUMN titulo TYPE TEXT;
ALTER TABLE artigos ALTER COLUMN veiculo TYPE TEXT;
ALTER TABLE tipos_producao ALTER COLUMN nome TYPE TEXT;
ALTER TABLE areas_conhecimento ALTER COLUMN nome TYPE TEXT;

-- 3. Bolsa é única por nome + financiador, como no ETL, e não só por nome.
ALTER TABLE bolsas DROP CONSTRAINT bolsas_nome_key;
ALTER TABLE bolsas ADD CONSTRAINT uq_bolsas_nome_financiador UNIQUE (nome, financiador_id);
